name: Hello world from JS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  say-hello-world-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install dependencies
        uses: npm i
      - name: Run file
        uses: node src/index.js
